# -*- coding: utf-8 -*-
{
    "name": "Theme Gunwerks Custom",
    "summary": "Theme Gunwerks Customization",
    "version": "11.0.1.0.0",
    "author": "Pledra",
    "website": "http://www.pledra.com",
    "depends": [
        'product_configurator',
        'product_configurator_mrp',
        'product_configurator_purchase',
        'product_configurator_sale',
        'product_configurator_stock',
        'product_configurator_image_builder',
        'website_product_configurator',
        'theme_gunwerks',
        'event_review_management',
        'product_review_management',
        'web_html_snippet',
        'website_animate',
        'website_product_publish',
        # 'website_video_extend',
    ],
    "data": [
        'views/assets.xml',
        'views/blog_list.xml',
    ],
    "demo": [
        'demo/product_attribute_demo.xml',
        'demo/product_attribute_value_demo.xml',
        'demo/product_template_demo.xml',
        'demo/product_attribute_lines_demo.xml',
        'demo/attribute_value_lines_demo.xml',
        'demo/product_config_domain_demo.xml',
        'demo/product_config_domain_line_demo.xml',
        'demo/product_config_line_demo.xml',
        'demo/product_config_step_demo.xml',
        'demo/product_template_config_line.xml',
        'demo/base_product_attribute_demo.xml',
    ],
    "qweb": [],
    "installable": True,
    'application': True,
}
